{
 "title": "OFDM Adaptive",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "collection" }
  ]
 },
 "panels": [
  {
   "title": "Estimated SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "db.$collection.aggregate([{$match: {insert_ts: {$gte: ISODate(\"${__from:date:iso}\"), $lt: ISODate(\"${__to:date:iso}\")}}}, {$match: {estimated_snr_tag_key: { $exists: true}}}, {$project: {\"time\":\"$insert_ts\", \"value\":\"$estimated_snr_tag_key\", _id:0}}])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Bits per QAM symbol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "target": "db.$collection.aggregate([{$match: {insert_ts: {$gte: ISODate(\"${__from:date:iso}\"), $lt: ISODate(\"${__to:date:iso}\")}}}, {$match: {bps: { $exists: true}}}, {$project: {\"time\":\"$insert_ts\", \"value\":\"$bps\", _id:0}}])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "FEC Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "target": "db.$collection.aggregate([{$match: {insert_ts: {$gte: ISODate(\"${__from:date:iso}\"), $lt: ISODate(\"${__to:date:iso}\")}}}, {$match: {tb_code_k: { $exists: true}}}, {$match: {tb_code_n: { $exists: true}}}, {$project: {\"insert_ts\":\"$insert_ts\", \"fec_rate\": {$divide: [ {$toInt:'$tb_code_k'}, {$toInt:'$tb_code_n'}]}}} ,{$project: {\"time\":\"$insert_ts\", \"value\":\"$fec_rate\", _id:0}}])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "db.$collection.aggregate([{$match: {insert_ts: {$gte: ISODate(\"${__from:date:iso}\"), $lt: ISODate(\"${__to:date:iso}\")}}}, {$match: {one_way_latency: { $exists: true}}}, {$project: {\"time\":\"$insert_ts\", \"value\":\"$one_way_latency\", _id:0}}])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Packet error rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "target": "db.$collection.aggregate([{$match: {insert_ts: {$gte: ISODate(\"${__from:date:iso}\"), $lt: ISODate(\"${__to:date:iso}\")}}}, {$match: {packet_error_rate: { $exists: true}}}, {$project: {\"time\":\"$insert_ts\", \"value\":\"$packet_error_rate\", _id:0}}])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Transport block CRC failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "target": "db.$collection.aggregate([{$match: {insert_ts: {$gte: ISODate(\"${__from:date:iso}\"), $lt: ISODate(\"${__to:date:iso}\")}}}, {$match: {crc_fail_count: { $exists: true}}}, {$project: {\"time\":\"$insert_ts\", \"value\":\"$crc_fail_count\", _id:0}}])",
     "type": "timeserie"
    }
   ]
  }
 ]
}